### ISSUE TITLE
MinSDK 23

### ISSUE THREAD

**Issue by ChangJoo-Park** [ChangJoo-Park/flutter_foreground_service_plugin#2]
uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [:flutter_foreground_plugin] /Users/changjoopark/StudioProjects/live_and_real/build/flutter_foreground_plugin/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 23,
		or use tools:overrideLibrary="changjoopark.com.flutter_foreground_plugin" to force usage (may lead to runtime failures)
Gradle task assembleDebug failed with exit code 1

**Comment by andzejsw** [comment]
Same for me if i don't use in manifest 
```
    <uses-sdk
        android:minSdkVersion="23"
        tools:overrideLibrary="changjoopark.com.flutter_foreground_plugin" />
```
Can minSdkVersion bounds be extended by package creators?

**Comment by andzejsw** [comment]
I also created pull request for issue fix: https://github.com/ChangJoo-Park/flutter_foreground_service_plugin/pull/5

**Comment by ChangJoo-Park** [comment]
Thanks @andzejsw  :) #5 merged
