### ISSUE TITLE
Close notification

### ISSUE THREAD

**Issue by eduardotq** [ChangJoo-Park/flutter_foreground_service_plugin#21]
I'm not sure this is an issue, maybe I just didnt found the way to do this.

The problem is that when the notification is showed, I cant close it, even later to close the app, the notification still there. 
On click it opens the app. Trying to slide it just show the options icon.

Is there some way to close the notification in the moment I click on it?

Thanks in advance

**Comment by eduardotq** [comment]
I would like to know too if there is a way to just schedule a task inside globalForegroundService without getting the notification everytime. For example, in my case, I need to make peridic api requests and only show a notification if I get a specific return from API.

**Comment by alkebuware** [comment]
Hey @eduardotq  I had the same issue where if the user kills the app the notification and icon would still persist. I found out that if I add the `android:stopWithTask="true"` to the service tag the notification goes away when the app is killed. Below is the a full example of the  updated service tag from the AndroidManifest.xml.


```
<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService"
               android:stopWithTask="true"/>
```

**Comment by ChangJoo-Park** [comment]
Thanks @alkebuware ! It is right answer.
