### ISSUE TITLE
The prefix "tools" for attribute "tools:overrideLibrary" associated with an element type "uses-sdk" is not bound.

### ISSUE THREAD

**Issue by danielmintz** [ChangJoo-Park/flutter_foreground_service_plugin#34]
Hi there,

I'm getting the following error using  flutter_foreground_plugin: ^0.8.0. Any ideas?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'buildConfigPackageName'.
   > Failed to query the value of property 'packageName'.
      > org.xml.sax.SAXParseException; systemId: file:/Users/danielmintz/go/SRC/ibikeride/android/app/src/main/AndroidManifest.xml; lineNumber: 103; columnNumber: 78; The prefix "tools" for attribute "tools:overrideLibrary" associated with an element type "uses-sdk" is not bound.

Flutter Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by rlch** [comment]
+1

**Comment by danielmintz** [comment]
> +1

@rlch did you have any luck resolving this?

**Comment by rlch** [comment]
Unfortunately I didn't, although I did come across this https://github.com/easazade/android-long-task which seems very promising - and seems to be better maintained. I haven't tried it out as I no longer need a foreground service, but hopefully this helps you out! :smile:

**Comment by danielmintz** [comment]
Hey I worked it out.. For anyone else in the dilemma.. First I downgraded to flutter_foreground_plugin: ^0.6.0.

Then I added this line that was missing in my AndroidManifest.xml file

` xmlns:tools="http://schemas.android.com/tools" `

as follows in the manifest tag

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.packagename.packagename"
    xmlns:tools="http://schemas.android.com/tools">
```
