### ISSUE TITLE
Update the version on pub.dev

### ISSUE THREAD

**Issue by firatcetiner** [ChangJoo-Park/flutter_foreground_service_plugin#6]
Please update the plugin on pub.dev as it is on GitHub. minSdk versions aren't match. Also I assume this plugin has no support for iOS, am I correct?

**Comment by ChangJoo-Park** [comment]
Yes you are. Foreground Service cannot support iOS

**Comment by ChangJoo-Park** [comment]
@firatcetiner I update this package same as pub.dev now.
