### ISSUE TITLE
How i can add close button to Notification?

### ISSUE THREAD

**Issue by DrobyshevAlex** [ChangJoo-Park/flutter_foreground_service_plugin#9]
I would to add button to notification that will close app. Is it possible to do?

**Comment by FabulousGee** [comment]
Currently this doesn't seem to be implemented since you need to do some work with custom ContentViews I think.
You will need to modify the plugin according to your needs or wait if the maintainer will allow this to happen in the future

**Comment by DrobyshevAlex** [comment]
Thank you. I made custom plugin.

**Comment by FabulousGee** [comment]
@DrobyshevAlex maybe you could share your implementation to give others an insight - maybe they even create a Pull Request.

**Comment by DrobyshevAlex** [comment]
@FabulousGee I never made pull request. I hope i do it right :)
https://github.com/ChangJoo-Park/flutter_foreground_service_plugin/pull/14
